import { 
  Building2, 
  LayoutDashboard, 
  BookOpen, 
  FileText, 
  Settings, 
  LogOut, 
  ShoppingBag,
  ShoppingCart,
  CreditCard,
  Users,
  Box,
  Warehouse,
  PieChart,
  Wallet,
  Globe,
  Monitor,
  History,
  Database,
  UserCircle,
  Palette,
  Calculator,
  BrainCircuit,
  MessageCircle,
  Kanban,
  Network,
  Fuel,
  HardHat,
} from "lucide-react";

export const COMPANIES = [
  { id: "1", name: "TechStart Innovations", industry: "Technology" },
  { id: "2", name: "GreenEarth Logistics", industry: "Logistics" },
  { id: "3", name: "Urban Retail Group", industry: "Retail" },
];

export const ACCOUNTS = [
  { code: "1001000", name: "Cash", nameTh: "เงินสด", type: "cash", parent: "100" },
  { code: "1001100", name: "Cash in transit", nameTh: "เงินฝากระหว่างทาง", type: "cash", parent: "100" },
  { code: "1001200", name: "Petty cash", nameTh: "เงินสดย่อย", type: "cash", parent: "100" },
  { code: "1001300", name: "E-Purse", nameTh: "เงินในกระเป๋าเงินอิเล็กทรอนิกส์", type: "cash", parent: "100" },
  { code: "1011000", name: "Saving Account - BBL", nameTh: "เงินฝากออมทรัพย์-ธนาคารกรุงเทพ", type: "cash", parent: "101" },
  { code: "1012000", name: "Saving Account - KBANK", nameTh: "เงินฝากออมทรัพย์-ธนาคารกสิกรไทย", type: "cash", parent: "101" },
  { code: "1013000", name: "Saving Account - SCB", nameTh: "เงินฝากออมทรัพย์-ธนาคารไทยพาณิชย์", type: "cash", parent: "101" },
  { code: "1014000", name: "Saving Account - KRUNGTHAI", nameTh: "เงินฝากออมทรัพย์-ธนาคารกรุงไทย", type: "cash", parent: "101" },
  { code: "1015000", name: "Saving Account - KRUNGSRI", nameTh: "เงินฝากออมทรัพย์-ธนาคารกรุงศรีอยุธยา", type: "cash", parent: "101" },
  { code: "1016000", name: "Saving Account - TMB", nameTh: "เงินฝากออมทรัพย์-ธนาคารทหารไทย", type: "cash", parent: "101" },
  { code: "1017000", name: "Saving Account - THANACHART", nameTh: "เงินฝากออมทรัพย์-ธนาคารธนชาต", type: "cash", parent: "101" },
];

export const NAV_ITEMS = [
  { 
    icon: LayoutDashboard, 
    label: "แผงควบคุม", 
    href: "/",
    children: [
      { label: "Analytical", href: "/dashboard/analytical" },
      { label: "eCommerce", href: "/dashboard/ecommerce" },
      { label: "HRM Dashboard", href: "/hr/dashboard" },
    ]
  },
  { 
    icon: Building2, 
    label: "บริหารสำนักงาน", 
    href: "/firm-mgmt",
    children: [
      { label: "มอบหมายงาน", href: "/firm-mgmt/assignments" },
      { label: "สัญญาจ้างทำบัญชี", href: "/firm-mgmt/contracts" },
      { label: "รายชื่อลูกค้าทั้งหมด", href: "/firm-mgmt/clients" },
      { label: "สรุปค่างวด/ค่าบริการ", href: "/firm-mgmt/billing" },
      { label: "คลังเอกสาร", href: "/firm-mgmt/documents" },
      { label: "ตั้งค่ากลุ่ม LINE", href: "/line-document-archive" },
      { label: "ปฏิทินภาษี", href: "/office/calendar" },
    ]
  },
  {
    icon: Kanban,
    label: "eTax Center",
    href: "/etax-hub",
  },
  { 
    icon: BookOpen, 
    label: "การบัญชี", 
    href: "/accounting",
    children: [
      { label: "สมุดบัญชีรายวัน", href: "/journal" },
      { label: "ผังบัญชี", href: "/coa" },
      { label: "สูตรบัญชีอัตโนมัติ", href: "/accounting/formulas" },
      { label: "บัญชีแยกประเภท", href: "/reports/general-ledger" },
      { label: "งบทดลอง", href: "/reports/trial-balance" },
      { label: "งบกำไรขาดทุน", href: "/reports/income-statement" },
      { label: "งบแสดงฐานะการเงิน", href: "/reports/balance-sheet" },
      { label: "การจัดการบัญชี", href: "/accounting-mgmt" },
    ]
  },
  { 
    icon: ShoppingCart, 
    label: "การขาย & รายได้", 
    href: "/sales",
    children: [
      { label: "Sales Pipeline", href: "/sales/pipeline" },
      { label: "ใบเสนอราคา [QO]", href: "/sales/quote" },
      { label: "ใบสั่งขาย [SO]", href: "/sales/order" },
      { label: "ใบแจ้งหนี้ [IV]", href: "/sales/invoice" },
      { label: "ใบส่งของ [DN]", href: "/delivery-notes" },
      { label: "ใบกำกับภาษี [TIV]", href: "/sales/tax-invoice" },
      { label: "รายการส่ง e-Tax", href: "/sales/etax-sent" },
      { label: "ใบเสร็จรับเงิน [RE]", href: "/sales/receipt" },
      { label: "ใบรับเงินมัดจำ [DP]", href: "/sales/deposit" },
      { label: "ใบลดหนี้ขาย [CN]", href: "/sales/credit-note" },
      { label: "รายงานภาษีขาย", href: "/sales/tax-report" },
      { label: "คอมมิชชั่นเซลส์", href: "/sales/commission" },
    ]
  },
  { 
    icon: ShoppingBag, 
    label: "การซื้อ & รายจ่าย", 
    href: "/purchases",
    children: [
      { label: "ใบขอซื้อ [PR]", href: "/purchases/pr" },
      { label: "เปรียบเทียบราคา [BID]", href: "/purchases/bid" },
      { label: "ใบสั่งซื้อ [PO]", href: "/purchases/po" },
      { label: "เอกสารซื้อ [AP]", href: "/purchases/invoice" },
      { label: "รายจ่ายอื่น (EXP)", href: "/purchases/expense" },
      { label: "ใบลดหนี้ซื้อ [DN]", href: "/purchases/debit-note" },
      { label: "จ่ายเงินมัดจำ [PDP]", href: "/purchases/purchase-deposit" },
      { label: "รายงานภาษีซื้อ", href: "/purchases/tax-report" },
      { label: "เงินสดย่อย", href: "/petty-cash", icon: Wallet },
      { label: "ภาษีหัก ณ ที่จ่าย (50 ทวิ)", href: "/purchases/wht" },
    ]
  },
  { 
    icon: CreditCard, 
    label: "การเงิน", 
    href: "/finance",
    children: [
      { label: "ปฏิทินครบกำหนดชำระ", href: "/finance/due-calendar", group: "ภาพรวม" },
      { label: "พยากรณ์เงินสด+ทุนหมุนเวียน", href: "/finance/cash-flow-forecast", group: "ภาพรวม" },
      { label: "ใบเสร็จรับเงิน", href: "/finance/receipt-billing", group: "รับ-จ่ายเงิน" },
      { label: "ใบวางบิล", href: "/finance/billing-notes", group: "รับ-จ่ายเงิน" },
      { label: "จ่ายเงิน/วางบิล", href: "/finance/ap-billing", group: "รับ-จ่ายเงิน" },
      { label: "รายการชำระเงิน", href: "/finance/payments", group: "รับ-จ่ายเงิน" },
      { label: "จัดการเช็ครับ/เช็คเงินโอน", href: "/finance/cheques", group: "เช็ค" },
      { label: "ประวัติเช็ค", href: "/finance/cheque-history", group: "เช็ค" },
    ]
  },
  { 
    icon: Users, 
    label: "ประวัติคู่ค้า", 
    href: "/contacts",
    children: [
      { label: "รายชื่อคู่ค้า", href: "/contacts/list" },
      { label: "ประวัติการดูคู่ค้า", href: "/contacts/history" },
      { label: "ตั้งค่าประวัติ", href: "/contacts/settings" },
    ]
  },
  { 
    icon: Box, 
    label: "คลังสินค้า", 
    href: "/inventory",
    children: [
      { label: "สรุปรายการสินค้า", href: "/inventory/list", group: "สินค้า" },
      { label: "สินค้าจัดชุด", href: "/inventory/bundles", group: "สินค้า" },
      { label: "โปรโมชั่น", href: "/inventory/promotions", group: "สินค้า" },
      { label: "คลังสินค้า", href: "/inventory/warehouse", group: "ควบคุมสินค้า" },
      { label: "ใบรับสินค้า (GR)", href: "/inventory/receiving", group: "ควบคุมสินค้า" },
      { label: "โอนย้ายสินค้า", href: "/inventory/stock-transfer", group: "ควบคุมสินค้า" },
      { label: "เบิกสินค้า", href: "/inventory/requisition", group: "ควบคุมสินค้า" },
      { label: "สต๊อกการ์ด", href: "/inventory/stock-card", group: "ควบคุมสินค้า" },
      { label: "สูตรผลิต (BOM)", href: "/inventory/bom", group: "การผลิต" },
      { label: "ใบสั่งผลิต", href: "/inventory/manufacturing", group: "การผลิต" },
      { label: "ล็อตการผลิต", href: "/inventory/lots", group: "การผลิต" },
      { label: "มูลค่าสินค้าคงเหลือ", href: "/inventory/reports/valuation", group: "รายงาน & เครื่องมือ" },
      { label: "สรุปการเคลื่อนไหว", href: "/inventory/reports/movement-summary", group: "รายงาน & เครื่องมือ" },
      { label: "สินค้าเคลื่อนไหวช้า", href: "/inventory/reports/slow-moving", group: "รายงาน & เครื่องมือ" },
      { label: "เชื่อมโยง/สต๊อก", href: "/inventory/product-mapping", group: "รายงาน & เครื่องมือ" },
      { label: "นำเข้า/ส่งออก Excel สินค้า", href: "/inventory/import-export", group: "รายงาน & เครื่องมือ" },
      { label: "ปริ้นท์ลาเบลบาร์โค้ด", href: "/inventory/barcode-labels", group: "รายงาน & เครื่องมือ" },
    ]
  },
  { 
    icon: Warehouse, 
    label: "ทะเบียนสินทรัพย์", 
    href: "/assets",
    children: [
      { label: "ทะเบียนสินทรัพย์", href: "/assets/registry", group: "ทรัพย์สิน" },
      { label: "หมวดหมู่ทรัพย์สิน", href: "/assets/categories", group: "ทรัพย์สิน" },
      { label: "สัญญาผ่อนชำระ", href: "/assets/installments", group: "ทรัพย์สิน" },
      { label: "รายงานค่าเสื่อมราคา", href: "/assets/depreciation", group: "รายงาน" },
      { label: "รายงานการขายทรัพย์สิน", href: "/assets/sales", group: "รายงาน" },
      { label: "รายงานทรัพย์สินหมดอายุ", href: "/assets/expired", group: "รายงาน" },
      { label: "สรุปรายการ", href: "/assets/summary", group: "รายงาน" },
      { label: "ประวัติการลงบัญชี", href: "/journal?search=DEP-", group: "รายงาน" },
    ]
  },
  { 
    icon: PieChart, 
    label: "รายงาน", 
    href: "/reports",
    children: [
      { label: "รายงานทั่วไป", href: "/reports/general" },
    ]
  },
  { 
    icon: Users, 
    label: "HR & เวลาทำงาน", 
    href: "/hr",
    children: [
      { label: "บริการตนเอง (ESS)", href: "/settings/profile", icon: UserCircle, group: "พนักงาน" },
      { label: "ทะเบียนพนักงาน", href: "/hr/employees", group: "พนักงาน" },
      { label: "หนังสือรับรอง", href: "/hr/certificates", group: "พนักงาน" },
      { label: "ลงเวลาเข้า-ออกงาน", href: "/hr/attendance", group: "เวลาทำงาน" },
      { label: "รายงานลงเวลา", href: "/hr/attendance-report", group: "เวลาทำงาน" },
      { label: "ขอลา / อนุมัติลา", href: "/hr/leave", group: "เวลาทำงาน" },
      { label: "จัดการ OT", href: "/hr/ot", group: "เวลาทำงาน" },
      { label: "ตั้งค่าเวลาทำงาน", href: "/hr/work-schedule", group: "กะ & ตั้งค่า" },
      { label: "ตั้งค่ากะทำงาน", href: "/hr/shift-settings", group: "กะ & ตั้งค่า" },
      { label: "ตารางจัดกะ", href: "/hr/shift-schedule", group: "กะ & ตั้งค่า" },
      { label: "ปฏิทินวันหยุด", href: "/hr/holidays", group: "กะ & ตั้งค่า" },
      { label: "จ่ายเงินเดือน / ภาษี", href: "/hr/payroll-tax", group: "เงินเดือน & ผลงาน" },
      { label: "กฎคอมมิชชั่น", href: "/hr/commission-rules", group: "เงินเดือน & ผลงาน" },
      { label: "คำนวณค่าคอมมิชชั่น", href: "/hr/commission", group: "เงินเดือน & ผลงาน" },
      { label: "AI ประเมินผลงาน", href: "/hr/performance", group: "เงินเดือน & ผลงาน" },
    ]
  },
  { 
    icon: Users, 
    label: "CRM ลูกค้า", 
    href: "/crm/customers",
    isAddon: true,
    children: [
      { label: "รายชื่อลูกค้า", href: "/crm/customers" },
      { label: "ต้นทุนโฆษณา & ROAS", href: "/ads/tracking" },
    ]
  },
  { 
    icon: Globe, 
    label: "eCommerce Hub", 
    href: "/ecommerce/dashboard",
    isAddon: true,
    children: [
      { label: "ออเดอร์ทั้งหมด", href: "/ecommerce/orders", group: "ออเดอร์ & การขาย" },
      { label: "นำเข้าออเดอร์", href: "/ecommerce/import", group: "ออเดอร์ & การขาย" },
      { label: "เอกสาร eCommerce", href: "/ecommerce/documents", group: "ออเดอร์ & การขาย" },
      { label: "คืนสินค้า/คืนเงิน", href: "/ecommerce/returns", group: "ออเดอร์ & การขาย" },
      { label: "Live Selling", href: "/ecommerce/live-selling", group: "ออเดอร์ & การขาย" },
      { label: "สต็อกสินค้า", href: "/ecommerce/inventory", group: "สินค้า & สต็อก" },
      { label: "คลังสินค้า", href: "/ecommerce/warehouses", group: "สินค้า & สต็อก" },
      { label: "แจ้งเตือนสต็อกต่ำ", href: "/ecommerce/stock-alerts", group: "สินค้า & สต็อก" },
      { label: "เชื่อมโยงสินค้า", href: "/ecommerce/hub", group: "สินค้า & สต็อก" },
      { label: "โคลนร้านค้า / สินค้า", href: "/ecommerce/store-clone", group: "สินค้า & สต็อก" },
      { label: "จัดส่งสินค้า", href: "/ecommerce/fulfillment", group: "จัดส่ง" },
      { label: "พิมพ์ใบปะหน้า", href: "/ecommerce/shipping-labels", group: "จัดส่ง" },
      { label: "ยอดเงินเข้า", href: "/ecommerce/settlements", group: "การเงิน" },
      { label: "กระทบยอดภาษี", href: "/ecommerce/reconciliation", group: "การเงิน" },
      { label: "วิเคราะห์ยอดขาย", href: "/ecommerce/analytics", group: "การเงิน" },
      { label: "คำนวณราคาขาย", href: "/ecommerce/price-calculator", group: "การเงิน" },
      { label: "เชื่อมต่อร้านค้า", href: "/ecommerce/connections", group: "ช่องทาง & เชื่อมต่อ" },
      { label: "Auto Sync", href: "/ecommerce/auto-sync", group: "ช่องทาง & เชื่อมต่อ" },
      { label: "Grab Food", href: "/ecommerce/grab-food", group: "ช่องทาง & เชื่อมต่อ" },
      { label: "Facebook Orders", href: "/ecommerce/facebook-orders", group: "ช่องทาง & เชื่อมต่อ" },
      { label: "Open API", href: "/ecommerce/api-connect", group: "ช่องทาง & เชื่อมต่อ" },
      { label: "Chat Inbox", href: "/ecommerce/chat", group: "ช่องทาง & เชื่อมต่อ" },
      { label: "ตั้งค่า eCommerce", href: "/ecommerce/settings", group: "ตั้งค่า" },
    ]
  },
  { 
    icon: BrainCircuit, 
    label: "Commerce Intelligence", 
    href: "/ci/executive",
    isAddon: true,
  },
  { 
    icon: Monitor, 
    label: "POS ขายหน้าร้าน", 
    href: "/pos/sessions",
    isAddon: true,
    children: [
      { label: "เปิดหน้าจอขาย", href: "/pos/terminal" },
      { label: "แดชบอร์ดยอดขาย", href: "/pos/dashboard" },
      { label: "รายการขาย", href: "/pos/sales" },
      { label: "ประวัติกะขาย", href: "/pos/sessions" },
      { label: "สมาชิก / Loyalty", href: "/pos/loyalty" },
      { label: "──── รายงาน POS ────", href: "#", group: "รายงาน POS" },
      { label: "ภาพรวมยอดขาย", href: "/pos-hub/dashboard" },
      { label: "ยอดขายแยกสาขา", href: "/pos-hub/sales-by-branch" },
      { label: "ยอดขายแยกสินค้า", href: "/pos-hub/sales-by-product" },
      { label: "ยอดขายแยกหมวดหมู่", href: "/pos-hub/sales-by-category" },
      { label: "สินค้าขายดี", href: "/pos-hub/best-sellers" },
      { label: "วิเคราะห์ช่องทางชำระ", href: "/pos-hub/payment-analysis" },
      { label: "ผลงานพนักงาน", href: "/pos-hub/cashier-performance" },
      { label: "ช่วงเวลาขายดี", href: "/pos-hub/hourly-trends" },
      { label: "สรุปรายวัน", href: "/pos-hub/daily-summary" },
    ]
  },
  {
    icon: HardHat,
    label: "ต้นทุนงาน",
    href: "/job-costing",
    isAddon: true,
    children: [
      { label: "โปรเจคทั้งหมด", href: "/job-costing" },
    ],
  },
  {
    icon: Fuel,
    label: "ปั๊มน้ำมัน",
    href: "/gas-station/dashboard",
    isAddon: true,
    children: [
      { label: "ภาพรวม", href: "/gas-station/dashboard" },
      { label: "ตั้งค่า", href: "/gas-station/setup" },
      { label: "ยอดขายรายวัน", href: "/gas-station/daily-sales" },
      { label: "สต็อกน้ำมัน", href: "/gas-station/fuel-stock" },
      { label: "Oil Loss/Gain", href: "/gas-station/oil-loss-gain" },
      { label: "ภาษีท้องถิ่น", href: "/gas-station/local-tax" },
      { label: "รายงาน", href: "/gas-station/reports" },
    ],
  },
  { 
    icon: Calculator, 
    label: "Tax Tools", 
    href: "/tax-tools",
    children: [
      { label: "นำเข้า 50 ทวิ / ภงด.1ก", href: "/tax-tools/wht-import" },
      { label: "สร้างงบการเงิน (นำเข้า Excel)", href: "/tax-tools/financial-statements" },
      { label: "ดึงใบเสร็จราชการ", href: "/tax-tools/gov-receipt" },
    ]
  },
  {
    icon: MessageCircle,
    label: "แชทภายใน",
    href: "/office/chat",
  },
  {
    icon: Users,
    label: "ห้องประชุม",
    href: "/office/meetings",
  },
  { 
    icon: Settings, 
    label: "ตั้งค่า", 
    href: "/settings/profile",
  },
  { 
    icon: History, 
    label: "บันทึกกิจกรรม", 
    href: "/activity-log",
  },
  { 
    icon: Network, 
    label: "ผังระบบ (Software House)", 
    href: "/system-info",
  },
];
